---
title: "2016 Global Ecological Footprint"
author: "Louise, Gary, Dominik"
date: "August 25, 2017"
output: 
  html_notebook: 
    number_sections: yes
    toc: yes
---


```{r setup}
# knitr is ths package that converts the rmarkdown document.
knitr::opts_chunk$set(echo = TRUE) # The knitr option echo = TRUE ensures both output and code will be printet. echo = FALSE prints only output
path_to_data <- "/home/dominik/Dropbox/Kandidat/Managing_big/datagroup_exam/"
# path_to_data <- ""
# path_to_data <- ""
# You can provide a relative path with knitr::opts_chunk$set(root.dir = normalizePath(".."))
knitr::opts_knit$set(root.dir = path_to_data)
knitr::opts_knit$get("root.dir") # prints the working directory
```

# Data
The data is downloaded from [Kaggle](https://www.kaggle.com/footprintnetwork/ecological-footprint). The description on the website states:
<!--

> The ecological footprint measures the ecological assets that a given population requires to produce the natural resources it consumes (including plant-based food and fiber products, livestock and fish products, timber and other forest products, space for urban infrastructure) and to absorb its waste, especially carbon emissions. The footprint tracks the use of six categories of productive surface areas: cropland, grazing land, fishing grounds, built-up (or urban) land, forest area, and carbon demand on land.

> A nation’s biocapacity represents the productivity of its ecological assets, including cropland, grazing land, forest land, fishing grounds, and built-up land. These areas, especially if left unharvested, can also absorb much of the waste we generate, especially our carbon emissions.

> Both the ecological footprint and biocapacity are expressed in global hectares — globally comparable, standardized hectares with world average productivity.

> If a population’s ecological footprint exceeds the region’s biocapacity, that region runs an ecological deficit. Its demand for the goods and services that its land and seas can provide — fruits and vegetables, meat, fish, wood, cotton for clothing, and carbon dioxide absorption — exceeds what the region’s ecosystems can renew. A region in ecological deficit meets demand by importing, liquidating its own ecological assets (such as overfishing), and/or emitting carbon dioxide into the atmosphere. If a region’s biocapacity exceeds its ecological footprint, it has an ecological reserve.

-->

```{r Read data}
getwd()
countries <- read.csv(file = "countries.csv")
```

```{r First look at the data}
dim(countries) # rows and columns
str(countries) # variable and their mode.
```

Let's convert `Country` to a character and `GDP.per.Capita` to numeric. Notice that the GDP variable has a $ sign we need to eliminate. 

```{r Changing mode of some variables}
countries$Country <- as.character(countries$Country)
library("stringr")
countries$GDP.per.Capita <- as.character(countries$GDP.per.Capita)
gsub(x = countries$GDP.per.Capita[1], pattern = "$", replacement = "")
gsub(x = "mig", pattern = "ig", replacement = "y")
?gsub
```






